var gulp=require('gulp');
var gutil=require('gulp-util');
var concat=require('gulp-concat');
var uglify=require('gulp-uglify');
var imagemin=require('gulp-imagemin');
var pngquant=require('imagemin-pngquant');
var sourcemaps=require('gulp-sourcemaps');
var del=require('del');
var md5=require('MD5');
var less=require('gulp-less');
var minifyCSS=require('gulp-minify-css');
var concatCss=require('gulp-concat-css');
var rename=require("gulp-rename");
var watch=require('gulp-watch');
var batch=require('gulp-batch');
var p=require('./package.json');
var paths=p.paths;
gulp.task('scripts',function(){var scripts=paths.vendor.scripts.concat(paths.src.scripts);
  gutil.log(gutil.colors.yellow('Compiling yours scripts'));
  return gulp.src(scripts).pipe(concat('app.js')).pipe(gulp.dest(paths.dist.scripts)).pipe(uglify()).pipe(rename("app.min.js")).pipe(gulp.dest(paths.dist.scripts));
});
gulp.task('styles',function(){gutil.log(gutil.colors.yellow('Compiling your less'));
var styles=paths.vendor.styles.concat(paths.src.styles);
return gulp.src(styles).pipe(less()).pipe(concatCss("app.css",{rebaseUrls:false})).pipe(gulp.dest(paths.dist.styles)).pipe(minifyCSS()).pipe(rename("app.min.css")).pipe(gulp.dest(paths.dist.styles));
});
gulp.task('images',function(){gutil.log(gutil.colors.yellow('Optimizing your images'));
return gulp.src(paths.src.images).pipe(imagemin({progressive:true,svgoPlugins:[{removeViewBox:false}],use:[pngquant()]})).pipe(gulp.dest(paths.dist.images));
});
gulp.task('videos',function(){gutil.log(gutil.colors.yellow('Moving your videos'));
return gulp.src(paths.src.videos).pipe(gulp.dest(paths.dist.videos));
});
gulp.task('fonts',function(){gutil.log(gutil.colors.yellow('Moving your fonts'));
gulp.src(paths.src.fonts).pipe(gulp.dest(paths.dist.fonts));
return gulp.src(paths.vendor.fonts).pipe(gulp.dest(paths.dist.fonts));
});
gulp.task('data',function(){gutil.log(gutil.colors.yellow('Moving your data'));
return gulp.src(paths.src.data).pipe(gulp.dest(paths.dist.data));
});
gulp.task('build',['scripts','styles','images','fonts'],function(){gutil.log(gutil.colors.yellow('Building your dist folder'));
});
//2
